name: moviepilot_mobile
description: MoviePilot Flutter mobile client
publish_to: none
version: 1.0.0+1
license: BSL-1.1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  get: ^4.6.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cookie_jar: ^4.0.8
  realm: ^20.2.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  talker_dio_logger: ^5.1.13
  syncfusion_flutter_charts: ^31.1.25
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  modal_bottom_sheet: ^3.0.0
  skeletonizer: ^2.1.2
  url_launcher: ^6.3.2
  liquid_tabbar_minimize: ^1.0.9
  path_provider: ^2.1.2
  palette_generator: ^0.3.3+7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.8
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.12.0
flutter:
  uses-material-design: true
  assets:
  - assets/logo.svg
  - assets/images/avatars/
  - assets/images/pages/
  - assets/images/logos/
  - assets/images/misc/
  - assets/images/svg/
flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
